name: flutter_boilerplate
description: Flutter boilerplate for apps with riverpod and clean architecture

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Routing
  auto_route: ^2.2.0
  #API
  dio: ^4.0.0
  # Localization
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # State Management
  flutter_riverpod: ^0.13.1+1
  # Local Storage
  flutter_secure_storage: ^4.1.0
  # App Updates
  in_app_update: ^2.0.0
  # API
  json_annotation: ^4.0.1
  # Debugging and Testing
  logging: ^1.0.1
  #UI
  overlay_support: ^1.2.0
  # Local Storage
  shared_preferences: ^2.0.5
  # App Updates
  upgrader: ^3.1.0






dev_dependencies:
  auto_route_generator: 2.1.0 
  build_runner: ^2.0.4
  change_app_package_name: ^0.1.2
  flutter_native_splash: ^1.1.5+1
  flutter_test:
    sdk: flutter

  json_serializable: ^4.1.0
  lint: ^1.5.3




################# Assets ###################

flutter:
  uses-material-design: true

  assets:
   - assets/translations/
   - assets/fonts/
   - assets/images/
   - assets/animations/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
    
  

flutter_native_splash:
  image: assets/images/kortobaa.png
  color: "ffffff"