name: flutter_boilerplate
description: Flutter boilerplate for apps with riverpod and clean architecture

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter




################# My Dependencies ################

  # UI
  intl: ^0.17.0
  overlay_support: ^1.2.0


  # State Management
  flutter_riverpod: ^0.13.1+1


  # Localization
  easy_localization: ^3.0.0


  # Local Storage
  shared_preferences: ^2.0.5
  flutter_secure_storage: ^4.1.0

  # API
  json_annotation: ^4.0.1
  dio: ^4.0.0


  # Debugging and Testing
  logging: ^1.0.0

  # App Updates
  in_app_update: ^2.0.0
  #upgrader: ^3.1.0


dev_dependencies:
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter

  json_serializable: ^4.1.0
  lint: ^1.5.3
  change_app_package_name: ^0.1.2
  flutter_native_splash: ^1.1.5+1



################# Assets ###################

flutter:
  uses-material-design: true

  assets:
   - assets/translations/
   - assets/fonts/
   - assets/images/
   - assets/animations/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
    
  

flutter_native_splash:
  image: assets/images/kortobaa.png
  color: "ffffff"