name: provider_boilerplate
description: Flutter boilerplate for apps with provider and clean architecture

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter




################# My Dependencies ################

  # UI
  overlay_support: ^1.0.5
  intl: ^0.16.1

  # State Management
  flutter_riverpod: ^0.12.1


  # Localization
  flutter_translate: ^1.6.0

  # Local Storage
  shared_preferences: ^0.5.10

  # API
  json_annotation: ^3.1.1
  dio: ^3.0.10


  # Debugging and Testing
  logging: ^0.11.4

  # App Updates
  in_app_update: ^1.1.14
  upgrader: ^2.7.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6
  json_serializable: ^3.5.0
  lint: ^1.2.0
  change_app_package_name: ^0.1.2
  flutter_native_splash: ^0.1.9



################# Assets ###################

flutter:
  uses-material-design: true

  assets:
   - assets/i18n/
   - assets/images/
   - assets/animations/



flutter_native_splash:
  image: assets/images/splash.png
  color: "42a5f5"