name: flutter_boilerplate
description: Flutter boilerplate for apps with riverpod and clean architecture

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Routing
  auto_route: ^4.2.1
  #API
  dio: ^4.0.6
  json_annotation: ^4.6.0

  # Localization
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^1.0.4
  event_bus: ^2.0.0

  # Local Storage
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.15

  # App Updates
  in_app_update: ^3.0.0


  # Debugging and Testing
  logging: ^1.0.2
  #UI
  overlay_support: ^2.0.1
  fluttertoast: ^8.0.9

  # App Updates
  upgrader: ^4.5.0
  # Share
  share_plus: ^4.0.10
  #packageInfo
  package_info_plus: ^1.4.3

  # depend reference
  intl: ^0.17.0
  easy_logger: ^0.0.2






dev_dependencies:
  auto_route_generator: ^4.2.1
  build_runner: ^2.2.0
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.2.7
  flutter_test:
    sdk: flutter

  json_serializable: ^6.3.1
  lint: ^1.10.0




################# Assets ###################

flutter:
  uses-material-design: true

  assets:
   - assets/translations/
   - assets/fonts/
   - assets/images/
   - assets/animations/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
    
  

flutter_native_splash:
  image: assets/images/kortobaa.png
  color: "ffffff"